name: devops
on:
  push:
    branches:
      - "kk"
jobs:
  devops:
    name: apply changes to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Execute Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform init
        run: terraform init
      - name: Terraform validate
        run: terraform validate
      - name: Terraform apply
        run: terraform apply -auto-approve